# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44199b9f85a5d81242fc217a1823f1f607feb05ff01a7a939f91395637037989ae6e5d9fb1deed4264086896da8d8fd73d44787476646eafa89c85132c884b7d

test:
  secret_key_base: daa82bc575f93844b6e47eba14870c8a7ae1069cee8e7e2752c383b4493837911f787a83b52238d27863a373d534900d21ff190410b5d860bcd8e07badc44a5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
